accessControl:
  enabled: false
api:
  allowCrossOrigin: true
  key: 1D8DF67AD9594E81A44830CF33936F55
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1560338100
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1549966200
      _plugins:
        read_until: 1560211200
      _releases:
        read_until: 1557824400
  cura:
    cura_engine: /opt/cura/CuraEngine
  discovery:
    upnpUuid: 452f54a5-65e9-4251-918d-578923a26612
  errortracking:
    unique_id: 692da1b5-46e8-41b4-99f9-06d8b4ac19d4
  softwareupdate:
    _config_version: 6
  tracking:
    enabled: true
    unique_id: 25f5cf6d-4920-4410-8736-907e600b5970
printerProfiles:
  default: _default
serial:
  autoconnect: true
server:
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: Dnk5IiOXoMl7ZeKWLDugMEwjjgW3uWtE
  seenWizards:
    corewizard: 3
    cura: null
    softwareupdate: null
    tracking: null
slicing:
  defaultProfiles:
    cura: ultimaker
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
